version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"

  # Enable version updates for the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(.github): "
    labels:
      - "dependencies"

  # Enable version updates for the docs
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(docs): "
    labels:
      - "dependencies"
