name: Publish container
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
          gpg-passphrase: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
      - name: Login to Docker
        run: |
          # new login with new container registry url and PAT
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build and Publish Package
        run: mvn -B deploy -DskipTests