name: Publish container
on:
  push:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  GHCR_USER: korthout
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build Package
        run: mvn -B clean package -DskipTests
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Publish Package
        run: mvn -B jib:build