name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'releaseVersion: The new version to release, e.g. 1.0.0'
        type: string
        required: true
      nextDevelopmentVersion:
        description: 'nextDevelopmentVersion: The new version to use during development e.g. 1.1.0-SNAPSHOT'
        type: string
        required: true
      dryRun:
        description: "dryRun: Don't push commits and don't publish artifacts"
        type: boolean
        required: true
        default: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Set up Yarn env
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Set release version in pom.xml
        run: mvn versions:set -DnewVersion=${{ inputs.releaseVersion }} -DgenerateBackupPoms=false

      - name: Set release version in openapi.yaml
        uses: endaft/action-yamler@v1.0.5
        with:
          file: ./openapi.yaml
          path: info.version
          set: ${{ inputs.releaseVersion }}

      - name: Generate docs for new release version
        run: |
          yarn run clean-api-docs all
          yarn run gen-api-docs all
        working-directory: docs

      - name: Commit new release version
        run: echo "dist:\ ${{ inputs.releaseVersion }}" | git commit -F- --no-edit

      - name: Print new release version commit
        run: git show head | cat
      
      - if: ${{ inputs.dryRun == false }}
        name: Push commit
        run: git push

      - name: Set next development version in pom.xml
        run: mvn versions:set -DnewVersion=${{ inputs.nextDevelopmentVersion }} -DgenerateBackupPoms=false

      - name: Set next development version in openapi.yaml
        uses: endaft/action-yamler@v1.0.5
        with:
          file: ./openapi.yaml
          path: info.version
          set: ${{ inputs.nextDevelopmentVersion }}

      - name: Commit next development version
        run: echo "dist:\ ${{ inputs.nextDevelopmentVersion }}" | git commit -F- --no-edit

      - name: Print next development version commit
        run: git show head | cat

      - if: ${{ inputs.dryRun == false }}
        name: Push commit
        run: git push