name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'releaseVersion: The new version to release, e.g. 1.0.0'
        type: string
        required: true
      nextDevelopmentVersion:
        description: 'nextDevelopmentVersion: The new version to use during development e.g. 1.1.0-SNAPSHOT'
        type: string
        required: true
      dryRun:
        description: "dryRun: Don't push commits and don't publish artifacts"
        type: boolean
        required: true
        default: false
concurrency: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Set up Yarn env
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Set release version in pom.xml
        run: mvn versions:set -DnewVersion=${{ inputs.releaseVersion }} -DgenerateBackupPoms=false

      - name: Set release version in openapi.yaml
        uses: endaft/action-yamler@v1.1.0
        with:
          file: ./openapi.yaml
          path: info.version
          set: ${{ inputs.releaseVersion }}

      - name: Generate docs for new release version
        run: |
          yarn run clean-api-docs all
          yarn run gen-api-docs all
        working-directory: docs

      - name: Commit new release version
        id: commit-new-release
        uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          default_author: github_actions
          fetch: false
          message: 'dist: ${{ inputs.releaseVersion }}'
          push: ${{ inputs.dryRun == false }}
          tag: v${{ inputs.releaseVersion }}

      - name: Print new release version commit
        run: git show ${{ steps.commit-new-release.outputs.commit_sha }} | cat

      - name: Set next development version in pom.xml
        run: mvn versions:set -DnewVersion=${{ inputs.nextDevelopmentVersion }} -DgenerateBackupPoms=false

      - name: Set next development version in openapi.yaml
        uses: endaft/action-yamler@v1.1.0
        with:
          file: ./openapi.yaml
          path: info.version
          set: ${{ inputs.nextDevelopmentVersion }}

      - name: Commit next development version
        id: commit-next-dev
        uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          default_author: github_actions
          fetch: false
          message: 'dist: ${{ inputs.nextDevelopmentVersion }}'
          push: ${{ inputs.dryRun == false }}

      - name: Print next development version commit
        run: git show ${{ steps.commit-next-dev.outputs.commit_sha }} | cat
