name: Test docs
on:
  pull_request:
    branches: [main]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: |
          cd docs
          yarn install --frozen-lockfile
      - name: Build
        run: |
          cd docs
          yarn build